USE [master]
GO

/****** Object:  Database [DSApp_PCD_py]    Script Date: 08/02/2019 09:40:37 ******/
CREATE DATABASE [DSApp_PCD_py] ON  PRIMARY 
( NAME = N'DSApp_PCD_py', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DSApp_PCD_py.mdf' , SIZE = 25600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DSApp_PCD_py_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DSApp_PCD_py_log.ldf' , SIZE = 47616KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DSApp_PCD_py] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DSApp_PCD_py].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DSApp_PCD_py] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET ARITHABORT OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DSApp_PCD_py] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DSApp_PCD_py] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DSApp_PCD_py] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DSApp_PCD_py] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DSApp_PCD_py] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DSApp_PCD_py] SET  READ_WRITE 
GO

ALTER DATABASE [DSApp_PCD_py] SET RECOVERY FULL 
GO

ALTER DATABASE [DSApp_PCD_py] SET  MULTI_USER 
GO

ALTER DATABASE [DSApp_PCD_py] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DSApp_PCD_py] SET DB_CHAINING OFF 
GO


